const WAIT_TIMEOUT = {
  SHORT: 3000,
  LONG: 5000,
};

const ALERT_TIMEOUT = {
  SHORT: 15000,
  LONG: 30000,
};

const DEBOUNCE_TIMEOUT = {
  SHORT: 800,
  EDITOR_SAVE: 1000,
};

const STATUS_TEXT_TIMEOUT = {
  SHORT: 5000,
};

export { WAIT_TIMEOUT, ALERT_TIMEOUT, DEBOUNCE_TIMEOUT, STATUS_TEXT_TIMEOUT };
