import type { TBaseNodeOptions } from '../extensions/baseNode';
import type { TBlockMenuOptions } from '../extensions/blockMenu';
import type { TBlockPlaceholderOptions } from '../extensions/blockPlaceholder';
import type { TBlockQuoteOptions } from '../extensions/blockQuote';
import type { TBoldOptions } from '../extensions/bold';
import type { TBubbleMenuOptions } from '../extensions/bubbleMenu';
import type { TBulletListOptions } from '../extensions/bulletList';
import type { TCodeBlockOptions } from '../extensions/codeBlock';
import type { THeadingOptions } from '../extensions/header';
import type { THorizontalLineOptions } from '../extensions/horizontalLine';
import type { TImageOptions } from '../extensions/image';
import type { TInlineCodeOptions } from '../extensions/inlineCode';
import type { TItalicOptions } from '../extensions/italic';
import type { TLangToolOptions } from '../extensions/langTool';
import type { TLinkOptions } from '../extensions/link';
import type { TListItemOptions } from '../extensions/listItem';
import type { TNumberListOptions } from '../extensions/numberList';
import type { TParagraphOptions } from '../extensions/paragraph';
import type { TPlaceholderOptions } from '../extensions/placeholder';
import type { TStrikethroughOptions } from '../extensions/strikethrough';
import type { TSubscriptOptions } from '../extensions/subscript';
import type { TSuperscriptOptions } from '../extensions/superscript';
import type { TTocOptions } from '../extensions/toc';
import type { TTrailingNodeOptions } from '../extensions/trailingNode';
import type { TUnderlineOptions } from '../extensions/underline';
import type { TUndoRedoOptions } from '../extensions/undoRedo';

type TExtensionOptions = {
  paragraph: Partial<TParagraphOptions> & { isEnabled: boolean };
  header: Partial<THeadingOptions> & { isEnabled: boolean };
  bulletList: Partial<TBulletListOptions> & { isEnabled: boolean };
  numberList: Partial<TNumberListOptions> & { isEnabled: boolean };
  listItem: Partial<TListItemOptions> & { isEnabled: boolean };
  undoRedo: Partial<TUndoRedoOptions> & { isEnabled: boolean };
  link: Partial<TLinkOptions> & { isEnabled: boolean };
  bold: Partial<TBoldOptions> & { isEnabled: boolean };
  italic: Partial<TItalicOptions> & { isEnabled: boolean };
  strikeThrough: Partial<TStrikethroughOptions> & { isEnabled: boolean };
  subscript: Partial<TSubscriptOptions> & { isEnabled: boolean };
  superScript: Partial<TSuperscriptOptions> & { isEnabled: boolean };
  underline: Partial<TUnderlineOptions> & { isEnabled: boolean };
  baseNode: Partial<TBaseNodeOptions> & { isEnabled: boolean };
  trailingNode: Partial<TTrailingNodeOptions> & { isEnabled: boolean };
  inlineCode: Partial<TInlineCodeOptions> & { isEnabled: boolean };
  codeBlock: Partial<TCodeBlockOptions> & { isEnabled: boolean };
  horizontalRule: Partial<THorizontalLineOptions> & { isEnabled: boolean };
  placeholder: Partial<TPlaceholderOptions> & { isEnabled: boolean };
  blockPlaceholder: Partial<TBlockPlaceholderOptions> & { isEnabled: boolean };
  image: Partial<TImageOptions> & { isEnabled: boolean };
  bubbleMenu: Partial<TBubbleMenuOptions> & { isEnabled: boolean };
  blockMenu: Partial<TBlockMenuOptions> & { isEnabled: boolean };
  blockQuote: Partial<TBlockQuoteOptions> & { isEnabled: boolean };
  langTool: Partial<TLangToolOptions> & { isEnabled: boolean };
  toc: Partial<TTocOptions> & { isEnabled: boolean };
};

export type { TExtensionOptions };
