version: "3"

silent: true

tasks:
  reset:
    description: reset main postgresql database
    prompt: this will reset the entire database. are you sure you want to continue?
    cmds:
      - |
        export DB_HOST="${BE_DB_SQL_MAIN_HOST}"
        export DB_PORT="${BE_DB_SQL_MAIN_PORT}"
        export DB_NAME="${BE_DB_SQL_MAIN_NAME}"
        export DB_USER="${BE_DB_SQL_MAIN_USER}"
        export DB_PASSWORD="${BE_DB_SQL_MAIN_PASSWORD}"
        export DB_SCRIPT="databases/main/setup/reset.pg.sql"
        . ./$FILE_SCRIPT_PSQL_SETUP
